### ISSUE TITLE
Default values for mass transfer coefficients

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/ABM#11]
Discussion on the calculation of default values

**Comment by sashahafner** [comment]
abm() includes volatilization of H2S and transport of O2 into manure/waste, where it is consumed by aerobic respiration. Both require mass transfer coefficients. 

For O2, we used the respiration rate measured by Rikke Markfoged (2013) based on the O2 profile (p87/21 Fig. 3). With a value of 0.1 nmol/s-cm^2 = 3.2E-5 g/s-m2, k_L = 3.25E-5 g/s-m2 / (27.2 g/m3-atm * 0.208 atm) = 5.7E-6 m/s = 0.49 m/d.

This calculation assume 20C for calculation of Henry's law constant (27.2, see code) and 1 atm total pressure with normal air. 

Assuming O2 transport is completely controlled by diffusion through a liquid film, this value corresponds to a film thickness of about 0.35 mm: thickness = D/k_L = 2E-9 m2/s / 5.7E-6 m/s = 3.5E-5 m.

**Comment by sashahafner** [comment]
For H2S, which is lost from the manure, transport over longer distances is more important. We simply assumed a film thickness of 1 cm: k_L = D/thickness = 2E-9 m2/s / 1E-2 m = 2E-7 m/s ~= 1.7E-2 m/d.

**Comment by sashahafner** [comment]
So for 378cd47d1660641158b10e5058adcd98faafeb81 the default values are 0.5 (O2) and 0.02 (H2S) m/d.

**Comment by sashahafner** [comment]
Markfoged, R., 2013. Microbial Control of Gas-Exchange at Air-Manure Interfaces. Aarhus University, Aarhus, Denmark.

**Comment by fdalby** [comment]
Solved and not relevant for O2 anymore.
