### ISSUE TITLE
VSd and CP etc. 

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/ABM#20]
Need to make sure it is never possible to specify both.
May be problem in add_pars

**Comment by fdalby** [comment]
This is solved around line 282 in  abm.R

if (any(pars$conc_fresh[['VSd']] > 1e-10) & any(pars$conc_fresh[names(pars$conc_fresh) %in% names(pars$A)[!names(pars$A) %in% c('VSd','urea')]] > 0)) {
    stop('Cannot have both VSd and other organic matter components being above 0')
  }

closing issue
