### ISSUE TITLE
Remove grz_pars

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/ABM#22]

**Comment by sashahafner** [comment]
@fdalby are these parameters still used in abm()?
I see this around L 230 in abm.R

```
  # calculate grazing interval of year if needed
  if(pars$graze_days > 0){
    pars$graze_int <- c(doy(pars$graze_start, 'March')$day, doy(pars$graze_start, 'March')$day + pars$graze_days)
  } else {
    pars$graze_int <- 0
  }

```

But I don't see "graze" in abm_*.R files.
If we do still need it is the hard-wired `'March'` a problem?

**Comment by fdalby** [comment]
> @fdalby are these parameters still used in abm()? I see this around L 230 in abm.R
> 
> ```
>   # calculate grazing interval of year if needed
>   if(pars$graze_days > 0){
>     pars$graze_int <- c(doy(pars$graze_start, 'March')$day, doy(pars$graze_start, 'March')$day + pars$graze_days)
>   } else {
>     pars$graze_int <- 0
>   }
> ```
> 
> But I don't see "graze" in abm_*.R files. If we do still need it is the hard-wired `'March'` a problem?

graze is in rates.R, I am using it for the abm carbon accounting stuff and would like to keep it. At least can we keep it as is until/or if I find a better solution?

**Comment by sashahafner** [comment]
Ah, OK. 
Sure, no problem to keep it. 
Does that hard-wired `'March'` need to be changed though? 
I am not sure what the code does so it might be fine.

**Comment by sashahafner** [comment]
Hmm, does it make sense to put grazing information in the "management" parameter argument?
Not sure.

**Comment by fdalby** [comment]
> Hmm, does it make sense to put grazing information in the "management" parameter argument? Not sure
Yes seems right to move to mng_pars. I will also remove the 'March'

**Comment by sashahafner** [comment]
OK, good, I see you already moved it.
Either in the help file or vignette could you explain the timing @fdalby ?
I don't remember how the grazing date works when the other timing info is all relative (just days, not date).

**Comment by fdalby** [comment]
Then 

> I will add the info to the help file.

Now added around L67

**Comment by fdalby** [comment]
Done
