### ISSUE TITLE
Effluent output "time" column duplicates

### ISSUE THREAD

**Issue by fdalby** [AU-BCE-EE/ABM#31]
@sashahafner. If we have emptying at day 28, the time column will be "...27, 28, 28, 29, 30..". Really it should be 28, 28.1 or something like that. 

If we extract out$time and use for a new simulation, it gives an error because we are passing identical times. Using the "time" column for a new simulation is relevant if we want to simulate emission from the effluents.

**Comment by fdalby** [comment]
See L125 in Vignette to simulate the problem.

**Comment by fdalby** [comment]
Make cumulative slurry_mass_effluent for easy use in next storage simulation.

**Comment by sashahafner** [comment]
@fdalby should we make a different data frame in output that only has emptied quantities?

**Comment by fdalby** [comment]
> @fdalby should we make a different data frame in output that only has emptied quantities?

@sashahafner that would probably be a good solution and make storage simulation easier

**Comment by sashahafner** [comment]
OK I can work on that.

**Comment by sashahafner** [comment]
Now we can use `value = 'eff'` (or `eff*` really) and only get effluent rows in the time series data.
I've added cumulative slurry mass to it.
It has a whole lot of columns--should we omit some?
Easiest to leave as is for now.

**Comment by fdalby** [comment]
This seems to work, @sashahafner ok to close it?

**Comment by sashahafner** [comment]
Sure.
