### ISSUE TITLE
Default parameter sets

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/ABM#35]
@fdalby pointed out that we should include default parameter sets in the package apart from in abm.R.
Users should know which set they are using and should be able to find and use older versions.
Here is an option.

1. Create a parameter object (list or vector) for each *_pars argument and include them all in the package as a data object. Would have a name and version, e.g., grp_pars2. Then users (and we!) would have an easy time using defaults for some parameters, e.g., grp_pars and mic_pars. 

2. Also create `pars2 <- list(wthr_pars, ... , grp_pars,...)` with all the individual par sets and include that in the pacakge as a data object. This could be the default in abm.R, included by `abm(pars = pars2,...)`

**Comment by sashahafner** [comment]
See 972345bee5bc6343ed14f8f05446cbaab594032d for an example.
This could then have in abm.R:

```
  init_pars = list(conc_init = man_pars$conc_fresh),
  grp_pars = grp_pars2.0, # Or ABM::grp_pars2.0
  mic_pars = list(ks_SO4 = 0.00694,
                  km_urea = 0.913,
                  alpha_opt = c(urea = 60, VSd = 0.04954023),
                  alpha_T_min = c(urea = 0, VSd = 0),
                  alpha_T_opt = c(urea = 50, VSd = 50),
                  alpha_T_max = c(urea = 60, VSd = 60)),
```

**Comment by fdalby** [comment]
Yup that is a good idea. I have added v2.0 pars as Rda and used them as defaults. I added some explanation in the vignette also.

**Comment by fdalby** [comment]
@sashahafner I guess this works well and I am closing the issue

**Comment by fdalby** [comment]
Oops you right should be just wthr_pars. Otherwise I also agree that the user need to actively think about mng_pars arguments and we should not give a pars vx.x set for that.

**Comment by fdalby** [comment]
> Could we keep it as `wthr_pars$temp_air_C` etc?
> That way if users use other `wthr_pars` the evap info will be pulled from that.

now fixed

**Comment by sashahafner** [comment]
> > Could we keep it as `wthr_pars$temp_air_C` etc?
> > That way if users use other `wthr_pars` the evap info will be pulled from that.
> 
> now fixed

Great

**Comment by sashahafner** [comment]
@fdalby I noticed the `scale` inputs in `mng_pars`.
Does that make sense?
I guess the idea is management could affect these things. . .

**Comment by sashahafner** [comment]
@fdalby should we (can we) have a (some) parsvXX objects made up of the parts (man_, grp_, etc.) for use with the `pars` argument? 
Do you use that argument at all?

**Comment by fdalby** [comment]
> @fdalby should we (can we) have a (some) parsvXX objects made up of the parts (man_, grp_, etc.) for use with the `pars` argument? Do you use that argument at all?

@sashahafner I have never used the pars argument - not even sure how it works :)? Question is if we need to do more work on that if we are not using it. It is ok for me if you want to.

**Comment by fdalby** [comment]
> @fdalby I noticed the `scale` inputs in `mng_pars`. Does that make sense? I guess the idea is management could affect these things. . .

@sashahafner . It might not make a lot of sense. Perhaps we should just remove it. Even putting it in grp_pars would still not make sense, because e.g. scale.alpha_opt, is not in grp_pars. I can remove if you agree.

**Comment by sashahafner** [comment]
Let's leave `pars` alone then.
Doesn't make sense to try to combine them in `pars` objects because the mangement parameters (others too?) would be missing. 
So that's solved for now.
