### ISSUE TITLE
Invert VS:COD ratios

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/ABM#8]
In input argument

**Comment by sashahafner** [comment]
We decided to make this inversion at our last meeting I think. 
Only 3 files have the conversion factors:

```
$ grep COD_conv *.R -l
abm.R
rates.R
stoich.R
```

**Comment by sashahafner** [comment]
I did a somewhat careful search-and-replace in the first two files abm.R and rates.R.
In nvim: `:%s/\* pars\$COD_conv/\/ pars\$COD_conv/gc` etc. (rates files doesn't have pars$ bit).

I did not change stoich.R. 
Not sure it is needed and it already has COD on the top:

```

# COD_conversion from moles to gCOD (acetate and H2) or moles to g (for CO2), 
# coefficients in gCOD/mol on reaction side and g/mol for CO2. 
# conversion factor (COD_conv_meth_CO2) has unit gCOD consumed/gCO2 produced
# conversion factor (COD_conv_sr_CO2) has unit gCOD consumed/gCO2 produced

COD_conv_meth_CO2 <- -(meth['C2H4O2'] * 64 + meth['H2'] * 16)/(meth['CO2'] * 44.01)
COD_conv_sr_CO2 <- -(sr['C2H4O2'] * 64 + sr['H2'] * 16)/(sr['CO2'] * 44.01)
```

All in 5140717ded27f8c164f1cf7811c5f820044271b9

**Comment by sashahafner** [comment]
We need to test this (and probably fix some bugs).
@fdalby I can pull a call from your vignette.
Any suggestions?

One possibility is to have a script that loads all ABM functions with `source()`.
Call it with the two different commits and check output with `all.equal()`.
Switch to a different commit with
```
$ git checkout 1c9c95801bd5336c5f9c87011fe5eb1058389681
```
for one just before change and
```
$ git checkout 5140717ded27f8c164f1cf7811c5f820044271b9
```
for one with change.

Note that I just added `1/` to all the default COD_conv values in abm.R.

**Comment by fdalby** [comment]
@sashahafner sounds good. You can pull the vignette yes. It is incomplete, but should run. 
Sound ok with the conversion and I think you can leave stoich as is. Can you run a test comparing before and after change - shoud give identical results.

**Comment by sashahafner** [comment]
Here goes. . .

```
# Changed version
ff <- list.files('../R', full.names = TRUE)
for (i in ff) source(i)

out1 <- abm(365)

# Get earlier version by running this in Bash:
# git checkout 1c9c95801bd5336c5f9c87011fe5eb1058389681

ff <- list.files('../R', full.names = TRUE)
for (i in ff) source(i)

out0 <- abm(365)

all.equal(out0, out1)
```

gives

```
> all.equal(out0, out1)
[1] "Component “VS_conc”: Mean relative difference: 1.100399"
[2] "Component “VS_load_rate”: Mean relative difference: 1.100399"
[3] "Component “VS_load_cum”: Mean relative difference: 1.100399"
[4] "Component “CH4_emis_rate_VS”: Mean relative difference: 0.5239"
[5] "Component “CH4_emis_cum_VS”: Mean relative difference: 0.5239"
[6] "Component “CO2_emis_rate_VS”: Mean relative difference: 0.5239"
[7] "Component “CO2_emis_cum_VS”: Mean relative difference: 0.5239"
[8] "Component “f_COD_CH4_rate”: Mean relative difference: 0.9371495"
```

Could be a lot worse I think!

**Comment by sashahafner** [comment]
Fixed L 322 in abm.R 
```
dat$VS_conc <- COD_conc / pars$COD_conv[['VS']] # this needs to be updated. Note this is both deg and undeg VS, whereas if VSd is given it is only deg VS
```

Getting closer:
```
> all.equal(out0, out1)
[1] "Component “VS_load_rate”: Mean relative difference: 1.100399"
[2] "Component “VS_load_cum”: Mean relative difference: 1.059341"
[3] "Component “CH4_emis_rate_VS”: Mean relative difference: 0.5239"
[4] "Component “CH4_emis_cum_VS”: Mean relative difference: 0.5111044"
[5] "Component “CO2_emis_rate_VS”: Mean relative difference: 0.5239"
[6] "Component “CO2_emis_cum_VS”: Mean relative difference: 0.5064489"
[7] "Component “f_COD_CH4_rate”: Mean relative difference: 0.9371495"
```

**Comment by sashahafner** [comment]
L 347 fixed
```
  dat$VS_load_rate <- dat$COD_load_rate / pars$COD_conv[['VS']]
```

Down to
```
> all.equal(out0, out1)
[1] "Component “f_COD_CH4_rate”: Mean relative difference: 0.9371495"
```

**Comment by sashahafner** [comment]
Finally, fixed L404:
```
  dat$f_COD_CH4_rate <-  dat$CH4_emis_rate * pars$COD_conv[['CH4']] / dat$COD_load_rate
```

and it works.

Here is all the code for checking again in case we need to do something similar later:

```
# Changed version
ff <- list.files('../R', full.names = TRUE)
for (i in ff) source(i)

out1 <- abm(365)

# Get earlier version by running this in Bash:
# git checkout 1c9c95801bd5336c5f9c87011fe5eb1058389681

ff <- list.files('../R', full.names = TRUE)
for (i in ff) source(i)

out0 <- abm(365)

all.equal(out0, out1)
```

**Comment by sashahafner** [comment]
See 08b3c7d0a10ba18863eabd15702a038a6ab256f5

**Comment by sashahafner** [comment]
Now I suppose we should change the values of the defaults.

**Comment by fdalby** [comment]
> Here goes. . .
> 
> ```
> # Changed version
> ff <- list.files('../R', full.names = TRUE)
> for (i in ff) source(i)
> 
> out1 <- abm(365)
> 
> # Get earlier version by running this in Bash:
> # git checkout 1c9c95801bd5336c5f9c87011fe5eb1058389681
> 
> ff <- list.files('../R', full.names = TRUE)
> for (i in ff) source(i)
> 
> out0 <- abm(365)
> 
> all.equal(out0, out1)
> ```
> 
> gives
> 
> ```
> > all.equal(out0, out1)
> [1] "Component “VS_conc”: Mean relative difference: 1.100399"
> [2] "Component “VS_load_rate”: Mean relative difference: 1.100399"
> [3] "Component “VS_load_cum”: Mean relative difference: 1.100399"
> [4] "Component “CH4_emis_rate_VS”: Mean relative difference: 0.5239"
> [5] "Component “CH4_emis_cum_VS”: Mean relative difference: 0.5239"
> [6] "Component “CO2_emis_rate_VS”: Mean relative difference: 0.5239"
> [7] "Component “CO2_emis_cum_VS”: Mean relative difference: 0.5239"
> [8] "Component “f_COD_CH4_rate”: Mean relative difference: 0.9371495"
> ```
> 
> Could be a lot worse I think!

Definitely could be a lot worse :) You found an easy way to run test with different code version i see? cool

**Comment by fdalby** [comment]
This was done. Closing
